Fix: add `.to_dict()` method to `PrioritizedISBN` for serialization
When checking `/status` on the affiliate-server, *if* there is an item
in the queue, the server would respond with an error because to display
items in the queue, they must be first serialized via `json.dumps`, but
prior to this commit, the `PrioritizedISBN` class could not be
serialized.

For reference, here is what would happen:
```
172.28.0.1:59064 - - [15/Mar/2024 22:20:29] "HTTP/1.1 GET /status" - 500 Internal Server Error
Traceback (most recent call last):
  File "/home/openlibrary/.local/lib/python3.12/site-packages/web/application.py", line 276, in process
    return self.handle()
           ^^^^^^^^^^^^^
  File "/home/openlibrary/.local/lib/python3.12/site-packages/web/application.py", line 267, in handle
    return self._delegate(fn, self.fvars, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/openlibrary/.local/lib/python3.12/site-packages/web/application.py", line 509, in _delegate
    return handle_class(cls)
           ^^^^^^^^^^^^^^^^^
  File "/home/openlibrary/.local/lib/python3.12/site-packages/web/application.py", line 487, in handle_class
    return tocall(*args)
           ^^^^^^^^^^^^^
  File "/openlibrary/./scripts/affiliate_server.py", line 305, in GET
    return json.dumps(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PrioritizedISBN is not JSON serializable
```

Now, as the accompany tests show, they can be serialized with the
`to_dict()` method.