fix AttributeError: 'NoneType' object has no attribute 'v2' (#4142)
Fixes: https://sentry.archive.org/sentry/ol-web/issues/3825

The filters might cause valid subjects not to be returned as evidenced by the test two lines further down.