Fix: make `isbndb.py` handle literal `None` values for `subjects`
This PR ensures `[]` is returned if either:
1. the `subjects` key is absent; or
2. the `subjects` key has a literal `None` value.

Sometimes `subjects` in the ISBNdb dump have literal `None` values,
which would cause an error even if doing something like
`data.get('subjects', [])`, because it would return `None` instead of
`[]`.

E.g., consider the following record:
```
{
 'isbn': '0134878868',
 'msrp': '0.00',
 'title': 'Learn Adobe Premiere Pro Cc For Video Communication',
 'isbn13': '9780134878867',
 'authors': ['Dockery, Joe (author.)'],
 'binding': 'Electronic Resource',
 'language': 'en',
 'subjects': None,
}
```
This would crash with:
```
        ^^^^^^^^^^^^^^^^^^^
  File "/openlibrary/scripts/providers/isbndb.py", line 73, in __init__
    self.subjects = [
                    ^
TypeError: 'NoneType' object is not iterable
```